### PR TITLE
Unmarshal YAML into map[string]interface{}

### LINKED ISSUE #196: `gopass show path/to/yaml key` : "cannot unmarshal !!map into string"
## Context 

From an updated install 
```
mfronton@lilbox:~$ go get -u github.com/justwatchcom/gopass
mfronton@lilbox:~$ gopass version
gopass HEAD (n/a ) go1.8.3
mfronton@lilbox:/opt/go/path/src/github.com/justwatchcom/gopass$ git describe
v1.2.0-18-gd249f00
```

From a newly created YAML password file : 
```
mfronton@lilbox:~$ gopass edit issue/yaml_support
mfronton@lilbox:~$ gopass show issue/yaml_support
---
pass: xxxxx
url: https://1.2.3.4/app
user: admin
foo:
  bar: baz
```

## What I do

I try to access any of the yaml key : 
```
mfronton@lilbox:~$ gopass show issue/yaml_support url
```
## What I get

I get an error message : 
```
mfronton@lilbox:~$ gopass show issue/yaml_support url

Error: yaml: unmarshal errors:
  line 5: cannot unmarshal !!map into string
```

## What I expected

The YAML is actually valid : 
```
mfronton@lilbox:~$ go get github.com/bronze1man/yaml2json
mfronton@lilbox:~$ apt-get install jq
mfronton@lilbox:~$ gopass show issue/yaml_support | yaml2json | jq '.'
{
  "pass": "xxxxx",
  "foo": {
    "bar": "baz"
  },
  "url": "http://1.2.3.4/app",
  "user": "admin"
}
```

So I expected the value of `url:` key to be displayed : 
```
mfronton@lilbox:~$ gopass show issue/yaml_support url
https://1.2.3.4/app
```

### PR DESCRIPTION
**Pull request by dominikschulz**
This improves handling of nested YAML documentens and makes error messages
more meaningful.

Fixes #196

### CODE REVIEW

File: store/err.go [hunk 1]
```diff
@@ -29,4 +29,6 @@ var (
 	ErrYAMLNoMark = fmt.Errorf("no YAML document marker found")
 	// ErrYAMLNoKey is returned if a YAML document doesn't contain a key
 	ErrYAMLNoKey = fmt.Errorf("key not found in YAML document")
+	// ErrYAMLKeyUnsupported is returned is the user tries to unmarshal an nested struct
+	ErrYAMLKeyUnsupported = fmt.Errorf("can not unmarshal nested YAML key")
```
Comment (zwopir) [inline store/err.go]: I suggest to call the error `ErrYAMLValueUnsupported`

Comment (dominikschulz) [inline store/err.go]: ok, will do
