### PR TITLE
Fix version parsing and comparison

### LINKED ISSUE #214: gopass version - Version check not working
The recently added version check does not properly parse the GitHub releases and will always report missed updates.

### PR DESCRIPTION
**Pull request by dominikschulz**
This commit introduces blang/semver for proper version parsing and
comparison and update the github-releases dependency to a version
using semver as well. Now the version check is asynchronous and has
a very short timeout.

Fixes #214

### CODE REVIEW

File: action/version.go [hunk 1]
```diff
@@ -3,33 +3,59 @@ package action
...
+	gitHubOrg  = "justwatchcom"
+	gitHubRepo = "gopass"
+)
+
 // Version prints the gopass version
 func (s *Action) Version(c *cli.Context) error {
+	version := make(chan string, 1)
+	go func(u chan string) {
+		if disabled := os.Getenv("CHECKPOINT_DISABLE"); disabled != "" {
+			u <- ""
```
Comment (zwopir) [inline action/version.go]: is `CHECKPOINT_DISABLE` documented somewhere?

Comment (dominikschulz) [inline action/version.go]: Good idea. Just added it to the README.
